# Generated by Django 4.1.4 on 2022-12-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('itemNumber', models.IntegerField()),
                ('bid', models.DecimalField(decimal_places=5, max_digits=5)),
                ('bidDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('itemNumber', models.IntegerField()),
                ('title', models.CharField(max_length=2000)),
                ('startingBid', models.DecimalField(decimal_places=5, max_digits=5)),
                ('startingDate', models.DateField()),
                ('auctionLength', models.IntegerField()),
                ('longDescription', models.CharField(max_length=4000)),
                ('shortDescription', models.CharField(max_length=3000)),
            ],
        ),
    ]
