# Generated by Django 4.1.4 on 2023-01-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_listing_itemnumber_remove_listing_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='startingBid',
            field=models.IntegerField(),
        ),
    ]
