# Generated by Django 4.1.4 on 2023-01-16 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listing_startingbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='userID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
