# Generated by Django 4.1.4 on 2023-01-19 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listing_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField(blank=True, null=True)),
                ('userName', models.CharField(blank=True, max_length=200, null=True)),
                ('itemNumber', models.IntegerField()),
                ('title', models.CharField(max_length=2000)),
            ],
        ),
    ]
