# Generated by Django 4.1.4 on 2023-01-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='userName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bids',
            name='userID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
