# Generated by Django 3.2.12 on 2023-02-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_listing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='deactivateItem',
            field=models.BooleanField(default=False),
        ),
    ]
