# Generated by Django 3.2.12 on 2023-03-03 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_bids_bid'),
    ]

    operations = [
        migrations.CreateModel(
            name='listingComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField(blank=True, null=True)),
                ('userName', models.CharField(blank=True, max_length=200, null=True)),
                ('itemNumber', models.IntegerField()),
                ('comment', models.CharField(max_length=2000)),
            ],
        ),
    ]
