# Generated by Django 3.2.12 on 2023-03-03 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_listingcomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingcomments',
            name='comment',
            field=models.CharField(max_length=3000),
        ),
    ]
